apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: assignment-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "host=postgres-service port=5432 user=postgres password=123 dbname=user_db sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
